### PR TITLE
devops-04-reducing-duplication

### PR DESCRIPTION
**Pull request by JonathanBanerjee**
@lgiordani
## What does this PR do?
Reduces duplication.

## How should this be manually tested?
By running `docker-compose up` to ensure the `docker-compose.yml ` file works.

## Any background context you want to provide?
This may have already been merged in accidence.

### CODE REVIEW

**Review by lgiordani — APPROVED** [review]

**Comment by lgiordani** [comment]
@JonathanBanerjee Remember to update the README telling the user they have to create the `.env` file and providing an example

**Comment by JonathanBanerjee** [comment]
Hi @lgiordani  I will format the README.md for aesthetics once the changes have been merged, that way I can preview the README.


I have attempted to get the application up and running but I am getting this path error:

`app_1     | 
app_1     | Error: Cannot find module '/usr/src/app/app.tsx'
app_1     |     at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
app_1     |     at Module._load (node:internal/modules/cjs/loader:920:27)
app_1     |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
app_1     |     at node:internal/main/run_main_module:23:47 {
app_1     |   code: 'MODULE_NOT_FOUND',
app_1     |   requireStack: []`

**Comment by lgiordani** [comment]
Well, I think this has to be solved with the author of the application. What is the command line used to run the app? I definitely see a problem in `docker-compose.yml` as

```
WORKDIR /usr/src/app
[...]
CMD [ "node", "app.tsx" ] 
```
Where is `app.tsx` in the code? The command above tries to run `/usr/src/app/app.tsx` but there is no such a file, hence the error.

**Comment by JonathanBanerjee** [comment]
Hi Leo, 

I believe the command line used to run the application is:

For the server:

```
$ git clone https://github.com/JonathanBanerjee/wordle
$ cd wordle
$ node ./server/server.js

```
For the app:

```
$ cd frontend
$ npm start
```

**Comment by JonathanBanerjee** [comment]
@lgiordani I was able to connect the app but I think I may need to have the server set up properly. Is there a different server client that you are familiar with configuring rather than using Prisma?

**Comment by lgiordani** [comment]
@JonathanBanerjee I'm not sure why you are getting rid of Prisma now, what does it have to do with the app?

**Comment by JonathanBanerjee** [comment]
I thought it was used as the server, but it was not configured correctly? So rather than having to contact my friend Matt, I thought it may be better to create a server so I can configure it to sync correctly with the other containers. 

I hope that makes sense.

**Comment by lgiordani** [comment]
Sorry no, it doesn't. I'm lost.
This thread started because the `app` component (not the `sever`, not the `db`) doesn't work.
I'm not sure why this started here in the first place, as this is a PR for reducing duplication, but at any rate you said `I have attempted to get the application up and running but I am getting this path error:`. So I commented on the app configuration, asking questions to help you move forward in the **configuration of the app**.
After that, you suggest to replace the interface between the `server` and the `db`.
Shall I not be confused?

**Comment by JonathanBanerjee** [comment]
Hi Leo, 

Apologies for the confusion. When I run the containers, using` docker-compose up` it displays the title but nothing else as shown in this screenshot.
Screenshot 2023-03-09 at 13 08 05

When I check the console logs it has a 404 error for the server. 
Screenshot 2023-03-09 at 13 09 29

And also an unhandled promise rejection:
Screenshot 2023-03-09 at 13 12 25


I commented out:

```
  // let solutions = undefined
  // try {
  //   solutions = await prisma;
  // } catch (error) {
  //   console.log(error)
  // }

  // const response = solutions || [{ id: 1, word: 'equip' }];
```

I am confused on how this part is to be configured so the wordle app can be displayed.

**Comment by lgiordani** [comment]
OK. So, first this is not the right PR to discuss that. The purpose of this PR is to reduce duplication in `server` and `db`. Which I think we did together already. Let's wrap up that task and merge it.
Second: if the application doesn't work we have to investigate that, starting from the error messages and discussing with the author of the application, unless you know enough Typescript to handle the errors that you showed. The solution implies **understanding the error** and is **not** commenting out code or removing parts of the server.
Shall we wrap up the duplication problem and then move on with the application in a proper branch?

**Comment by JonathanBanerjee** [comment]
Yes - ready to squash and merge, I will create a new PR later on :)

**Pull request merged**
